### PR TITLE
LPS-118759 check template uses react before writing provide capability

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-118759

### CODE REVIEW

**Comment by marcosapmf** [comment]
Hi @lawrence-lee,

Could please review this last pull about the custom form field template?

Thanks in advance :)

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
Hi @lawrence-lee, do you have any update regarding this pull?

Thanks in advance.

**Comment by lawrence-lee** [comment]
Hi @natocesarrego , I'll take a look at this today

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Forward'd https://github.com/lawrence-lee/liferay-portal/pull/185

**Comment by natocesarrego** [comment]
Thanks a lot, @lawrence-lee! 🙂

**Comment by marcosapmf** [comment]
Thank you very much, @lawrence-lee! :smile:

**Pull request closed without merging**
