### PR TITLE
LPS-116590 make the necessary changes to guarantee that project template generate works on 7.3 properly

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
LGTM!
I'll wait for the changes to the react and metaljs options before pushing this forward

**Comment by natocesarrego** [comment]
Thanks, @lawrence-lee! 😄 

Do you see any problem we move on with this pull and then we send the React form field template later? We'll do our best to deliver it ASAP, but we also have other tasks before work on the React template. This current pull allows customers using 7.3 get access to what we already have on 7.2.

Thanks.

**Comment by lawrence-lee** [comment]
@natocesarrego, Ahh okay! I understand. I'll go ahead and push this up today

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Updated here: https://github.com/lawrence-lee/liferay-portal/pull/178

**Comment by natocesarrego** [comment]
Great, @lawrence-lee! Thanks.

**Pull request closed without merging**
