### PR TITLE
Lps 139835 Update project template tokens

### PR DESCRIPTION
**Pull request by DL-EthanSun**

### CODE REVIEW

**Comment by DL-EthanSun** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by DL-EthanSun** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Pushed to https://github.com/petershin/liferay-portal/pull/1523

**Pull request closed without merging**
