### PR TITLE
LPS-76066 project-templates-test

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
hey @lawrence-lee  this is going to test everything (all jars and all wars), so the 'install' test is going to have to be a bit more careful to do the following

1) don't start fragments, just check to make sure they are 'resolved' not active I can show you code later if a bundle is a fragment
2) for wars, we need to install them as wabs, so we need to do just like in blade samples where we  install it using the `webbundle:file://....?Context-path=....`

**Comment by gamerson** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
resent here: https://github.com/gamerson/liferay-portal/pull/56

**Pull request closed without merging**
