### PR TITLE
LPS-147672 add distBundleTarAll and distBundleZipAll tasks

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@simonjhy , I think you broke distBundleZip `DistBundleZipTest` failed. Also, this is just a gradle-plugins-workspace change, no need for project-templates update

**Comment by lawrence-lee** [comment]
You dont need fd272bddae40d5db2c5b5f09d9e0e3788364a433 and a0d199493860dfd893f05691d54299d2f812beee. When you fix the tests, can you send to Dave for review?

**Pull request closed without merging**
