### PR TITLE
For Test

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@Seiphon , you need the commit to include the project-templates-*/build.gradle files.  otherwise it wont pass

**Comment by Seiphon** [comment]
> @Seiphon , you need the commit to include the project-templates-*/build.gradle files. otherwise it wont pass

I just want to set com.liferay.gradle.plugins.workspace.version=3.4.17, then the project-templates-workspace will use the 3.4.17 gradle workspace plugin. is that neccessary to update all project templates versions?

**Pull request closed without merging**
