### PR TITLE
LPS-142340 Support target platform verson end with u1

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
@simonjhy and @Seiphon , SF failed. can you guys take a look?

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by Seiphon** [comment]
resent the pr here https://github.com/lawrence-lee/liferay-portal/pull/238

**Pull request closed without merging**
