### PR TITLE
Lps 137135

### PR DESCRIPTION
**Pull request by DL-EthanSun**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
@DL-EthanSun, What is the purpose of this PR?

**Comment by DL-EthanSun** [comment]
Sorry, I would like to build blade.jar with the latest project-templates-rest-builder.At present, I clearly understand that I should upgrade project-templates version in blade cli build.grade.

**Comment by lawrence-lee** [comment]
@DL-EthanSun, Got it. Can we close this PR?

**Pull request closed without merging**
