### PR TITLE
LPS-154072 Add docker local registry support

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
Thanks. I'm going to add a few more action items

1. Lets add a test to make sure that when you add a local docker registry the Dockerfile reflects the changes
2. Lets make sure the address can handle these [localhost:5000, https://mylocaldomain:5000/, http://mylocaldomain:5000] You will need to configure your docker registry host to change the hostname.

**Comment by Seiphon** [comment]
> 

OK, will implement the test for dockerfile asap. And for different addresses, should we also add tests for that?

**Comment by lawrence-lee** [comment]
I think for the different addresses, you should just test it manually to make sure it works. Since this code is in the docker plugin api, we shouldnt add our own tests for it.

**Pull request closed without merging**
