### PR TITLE
LPS-74448 make more interesteing

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @lawrence-lee  can you generate this locally with `mvn archetype:generate` and then import them both into Liferay IDE to make sure they work as both maven and gradle projects.  Also can you update the tests accordingly to my changes.  Also can you deploy this to Liferay GA4 and make sure that it works?  Thanks!

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
Also could you build the war using `gw build` and compare the war that is built to a war that is built using the plugins-sdk and its hook template.  So we can compare

**Comment by lawrence-lee** [comment]
pushed here: https://github.com/gamerson/liferay-portal/pull/35

**Pull request closed without merging**
