### PR TITLE
LPS-107504 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Hi @wincent, 

I'm running into these errors that I think are caused by f7704c187c75117402a8d479ea8c76dcc368b824. Do you know what's going on here?

**Comment by wincent** [comment]
@lawrence-lee: f7704c1 definitely looks a likely cause. We changed all of our `.babelrc` to `.babelrc.js` in that commit; eg (diff with `--no-renames` to make it clear what actually happened):

```diff
diff --git a/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/angular/.babelrc b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/angular/.babelrc
deleted file mode 100644
index e69de29bb2d1..000000000000
diff --git a/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/angular/.babelrc.js b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/angular/.babelrc.js
new file mode 100644
index 000000000000..f053ebf7976e
--- /dev/null
+++ b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/angular/.babelrc.js
@@ -0,0 +1 @@
+module.exports = {};
diff --git a/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc
deleted file mode 100644
index 0159960bce01..000000000000
--- a/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc
+++ /dev/null
@@ -1,3 +0,0 @@
-{
-	"presets": ["env", "react"]
-}
diff --git a/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc.js b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc.js
new file mode 100644
index 000000000000..c94dc9b6d570
--- /dev/null
+++ b/modules/sdk/gradle-plugins-workspace/src/gradleTest/jsPortlet/modules/my-project/.babelrc.js
@@ -0,0 +1,3 @@
+module.exports = {
+	"presets": ["env", "react"]
+};
diff --git a/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc b/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc
deleted file mode 100644
index a3cdc5586d83..000000000000
--- a/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc
+++ /dev/null
@@ -1,3 +0,0 @@
-{
-	"presets": ["es2015", "liferay-project"]
-}
\ No newline at end of file
diff --git a/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc.js b/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc.js
new file mode 100644
index 000000000000..74e458d7791a
--- /dev/null
+++ b/modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/.babelrc.js
@@ -0,0 +1,3 @@
+module.exports = {
+	"presets": ["es2015", "liferay-project"]
+};
diff --git a/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/.babelrc b/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/.babelrc
deleted file mode 100644
index e69de29bb2d1..000000000000
diff --git a/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/.babelrc.js b/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/.babelrc.js
new file mode 100644
index 000000000000..f053ebf7976e
--- /dev/null
+++ b/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/.babelrc.js
@@ -0,0 +1 @@
+module.exports = {};
diff --git a/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc b/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc
deleted file mode 100644
index 51a07ce22046..000000000000
--- a/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc
+++ /dev/null
@@ -1,3 +0,0 @@
-{
-	"presets": ["env", "react"]
-}
\ No newline at end of file
diff --git a/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc.js b/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc.js
new file mode 100644
index 000000000000..c94dc9b6d570
--- /dev/null
+++ b/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc.js
@@ -0,0 +1,3 @@
+module.exports = {
+	"presets": ["env", "react"]
+};
diff --git a/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc b/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc
deleted file mode 100644
index 181cce65b823..000000000000
--- a/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc
+++ /dev/null
@@ -1,3 +0,0 @@
-{
-	"presets": ["env"]
-}
\ No newline at end of file
diff --git a/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc.js b/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc.js
new file mode 100644
index 000000000000..3d2966c61014
--- /dev/null
+++ b/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/.babelrc.js
@@ -0,0 +1,3 @@
+module.exports = {
+	"presets": ["env"]
+};
```

There are still references to ".babelrc" under `modules/sdk` which I didn't know about, so it looks like we also need to update all of those (ie. 6 places that you can see with `git grep babelrc modules/sdk`):

- modules/sdk/project-templates/project-templates-form-field/src/main/java/com/liferay/project/templates/form/field/internal/FormFieldProjectTemplateCustomizer.java
- modules/sdk/project-templates/project-templates-form-field/src/main/resources/META-INF/archetype-post-generate.groovy
- modules/sdk/project-templates/project-templates-form-field/src/main/resources/META-INF/maven/archetype-metadata.xml
- modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml
- modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml
- modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml

I've sent you [a PR with that change](https://github.com/lawrence-lee/liferay-portal/pull/146), but I don't know how to actually run these tasks locally (or if I need to do anything special to get CI to properly test them) so I'll see what happens in CI with it. I'm also [running tests in my own fork](https://github.com/wincent/liferay-portal/pull/124). If *that* doesn't work, then we can revert the renames under the `modules/sdk`directory and add a lint suppression for it (everywhere else in portal we know *force* the use of `.babelrc.js` instead of `.babelrc`).

**Comment by wincent** [comment]
@lawrence-lee: Given the time zone difference and the fact that we are heading into a weekend, I don't want you to get blocked so instead of that PR that I mentioned in my previous comment, I've sent [this](https://github.com/brianchandotcom/liferay-portal/pull/83736) to Brian reverting the changes from f7704c1  that were made under the "modules/sdk" directory. I'll close those other PRs. I think that should clear the way for you; let me know if it doesn't.

**Comment by lawrence-lee** [comment]
thanks for sending the revert@wincent. I will rebase this PR once brian merge. 

I want incorporate the newest liferay-npm-scripts into our project templates so let's see if we can get it working. Here's some info that maybe I should've started out with in my message yesterday. 

I already added some of these changes to my PR. See https://github.com/lawrence-lee/liferay-portal/pull/145/commits/414969511efb970043d2a8131d1e610a1fdd90e0. The changes in this commit only make sure the archetype is valid and can be generated. 

It seems that when we actually try to do `npm run build` on the generated npm react project, that's when the failures are occurring. To make things simple, let's just look at one test case testBuildTemplateNpmReactPortlet70 stacktrace https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/290385/testReport/com.liferay.project.templates/ProjectTemplatesTest/testBuildTemplateNpmReactPortlet70/

I think for now, let's wait until master is green again and then we can try this update again.

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
pushed here: https://github.com/gamerson/liferay-portal/pull/389

**Pull request closed without merging**
