### PR TITLE
IDE-4081 improve language key usage

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @lawrence-lee  can you look at these updated project templates and test them against 70GA7 and Master?  Also there are some existing projectTemplateTests test failures that will need to be addressed.  Thanks!

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
pushed: https://github.com/gamerson/liferay-portal/pull/136

**Pull request closed without merging**
