### PR TITLE
LPS-148033 form filed project should to update node_modules

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
i:test:project-templates

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
I checked the failed test case, they are related to the Npm React project maven and gradle output jar dependencies diffrences issue(I sent the template change pull request.)

**Comment by lawrence-lee** [comment]
Sent here: https://github.com/petershin/liferay-portal/pull/1606

**Comment by lawrence-lee** [comment]
Just a minor rename

**Pull request closed without merging**
