### PR TITLE
LPS-128040 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@javierdearcos, can you review this change to the `rest-builder` template? This is for jdk11 compatibility. I think java 9+ removed those dependencies.

**Comment by javierdearcos** [comment]
Hello Lawrence,

Sorry for the delay. 

Look good to me. I have the same feeling that there was many javax dependencies that were removed from jave 9+, so these additions look perfectly fine to me

**Comment by lawrence-lee** [comment]
Thanks!

**Comment by lawrence-lee** [comment]
Sent to https://github.com/petershin/liferay-portal/pull/1370

**Pull request closed without merging**
