### PR TITLE
LPS-153767

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test

**Comment by Seiphon** [comment]
ci:stop

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
> 

Sorry @lawrence-lee , I sent the wrong commit, I will resend it. By the way, ne thing I am a little confused about, should I only update project-templates-service-builder or update all project-templates?

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
> You should always update all the project templates. did you debug the test to make sure it has the fix?

I have tested, I'm sure it has the fix

**Comment by lawrence-lee** [comment]
@Seiphon can you take a look at the failing test?

**Comment by Seiphon** [comment]
sent the pr to Peter https://github.com/petershin/liferay-portal/pull/1664

**Pull request closed without merging**
