### PR TITLE
LPS-98417 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
cc @natocesarrego & @gabrielibson Brian made some changes here, but it still passes the tests. 

6f55ad9 and 243347f

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 https://issues.liferay.com/browse/LPS-110102
`Duplicate entry 'com.liferay.portal.repository.portletrepository.PortletRepositor' for key 'IX_B27A301F'`

**Comment by natocesarrego** [comment]
Thanks for letting us know about this progress, @lawrence-lee. 🙂

**Pull request closed without merging**
