### PR TITLE
LPS-116357 Add argument to RESTBuilder Project Template to generate client and test modules

### PR DESCRIPTION
**Pull request by javierdearcos**
I added a parameter named extraModules to REST Builder Project Template to decide whether you want to generate client and test modules or not. As this modules are more like a complex feature, this argument is false by default (if it is omitted).

In gradle when extraModules is true, the client and test modules are generated.

In Maven when extraModules is true, the client is generated. The test module is not because I think this kind of tests could not be run through Maven, but I left everything prepared to enable it if I find there is a way to run this tests or it is added in the future.

As you suggest, I create new tests to check everything and go with shorter and more focus tests.

I send you the PR so you can check the changes as this is more your field of expertise. If you want me to go directly with ci:forward please tell me. Anyway I hope this is the last PR for a while in this feature.

Thank you very much for your help! Have a great week!

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:project-templates

**Comment by javierdearcos** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
resent https://github.com/lawrence-lee/liferay-portal/pull/173

**Pull request closed without merging**
