### PR TITLE
LPS-105232 Use latest project-templates

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@javierdearcos It looks like its not executing `buildREST` correctly

Here's a snippet of the error 
```
Error Message

org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace with arguments [-Dhttp.proxyHost=squid.lax.liferay.com, -Dhttp.proxyPort=3128, --stacktrace, :modules:guestbook:guestbook-impl:buildREST]

Output:

> Task :modules:guestbook:guestbook-impl:buildREST
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-impl/src/main/java/com/liferay/docs/guestbook/internal/jaxrs/application/GuestbookApplication.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/json/BaseJSONParser.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/http/HttpInvoker.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/pagination/Page.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/pagination/Pagination.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/permission/Permission.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/problem/Problem.java
Writing /tmp/junit8818327691989913196/gradleWorkspacetest-workspace/test-workspace/modules/guestbook/guestbook-client/src/main/java/com/liferay/docs/guestbook/client/function/UnsafeSupplier.java
Exception in thread "main" java.lang.RuntimeException: Error generating REST API
Error in file "rest-openapi.yaml": Invalid YAML in 'string', line 8, column 25:
    openapi: 3.0.1components:
                            ^: mapping values are not allowed here
	at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:126)

> Task :modules:guestbook:guestbook-impl:buildREST FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:guestbook:guestbook-impl:buildREST'.```

**Comment by javierdearcos** [comment]
I'll send you a PR with all your changes and tests fixed right now

**Pull request closed without merging**
