### PR TITLE
Lps 132252

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @lawrence-lee , I have tested spring-mvc-portlet with the same target platform version with workspace, it works well

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Sent https://github.com/petershin/liferay-portal/pull/1501

Thanks @Seiphon

**Pull request closed without merging**
